spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://43.143.231.27:5432/blog?currentSchema=baozangzhinan&serverTimezone=Asia/Shanghai&useUnicode=true&characterEncoding=utf-8&useSSL=false
    password: lkdsg20001102
    username: lkk
  data:
    redis:
      host: 43.143.231.27
      port: 6379
      password: lkdsg20001102

login:
  AppID: wxf27ef0f2fe3cca66
  AppSecret: 74fe3af9d56437295df190e1adbefc6f

server:
  port: 8081
zinc:
  username: admin
  password: admin
  ip: https://zinc.xiaoliu.life/
  index: baozangzhinan