spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://127.0.0.1:5432/blog?currentSchema=baozangzhinan&serverTimezone=Asia/Shanghai&useUnicode=true&characterEncoding=utf-8&useSSL=false
    password:
    username:
  data:
    redis:
      host: 127.0.0.1
      port: 6379
      password: secret

login:
  AppID:
  AppSecret:

server:
  port: 8081
zinc:
  username:
  password:
  ip:
  index: